// Focuses on constructing output statements. Program Shell is the outline of a program.
// Use this shell for Question#1 through #3
// a. Question#1: Write a program to read-in from keyboard and print the
// following information single spaced on the screen. Use literal constants in the
// output statements for each of the data items to be written on the screen. Run
// your program to verify that the output is as specified.
// i. your name (last name, comma, blank, first name)
// ii. today’s date (month:day:year)
// b. Question#2: Change your program so that there is a space between the two
// lines of output.
// c. Question#3: Change your program so that your first name is printed followed
// by your last name, with a blank in between the names.

// Answer: 


# include<iostream> // (Question#2)
using namespace std;
int main() {
  string last_name, first_name, date;
  cout << "Enter your last name: ";
  cin >> last_name;
  cout << "Enter your first name: ";
  cin >> first_name;
  cout << "Enter today's date (month:day:year): ";
  cin >> date;

  cout << "1." << last_name << "," << " " << first_name << endl;
  cout << "2." << date << endl;

  cout << endl;
  cout << "3." << first_name << " " << last_name << endl;

  return 0;
}

// output - Enter your last name: Zaman
// Enter your first name: Afia
// Enter today's date (month:day:year): 02:10:2024
// 1.Zaman, Afia
// 2.02:10:2024

// 3.Afia Zaman
